-- AlterTable
ALTER TABLE "ClientService" ADD COLUMN     "autoInvoice" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "nextInvoiceDate" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
