import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { addDays, addMonths, format } from "date-fns";
import { prisma } from "@/lib/prisma";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Called by a scheduled GitHub Actions workflow (not a user), once a day — see
 * .github/workflows/generate-recurring-invoices.yml. Runs as an ordinary Next.js route
 * handler (the same Prisma path already proven working in production) rather than a
 * hand-written Netlify Function, deliberately avoiding the well-known "query engine
 * binary not found" class of failure that comes with bundling Prisma into a raw Lambda.
 *
 * For every ACTIVE, MONTHLY, auto-invoiced ClientService whose nextInvoiceDate has
 * arrived, creates one Invoice and advances nextInvoiceDate by exactly one month from
 * its own prior value (not from "today"), so billing stays anchored to the client's
 * original start date instead of drifting.
 */
export async function POST(req: Request) {
  if (req.headers.get("x-cron-secret") !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const now = new Date();
  const dueServices = await prisma.clientService.findMany({
    where: {
      status: "ACTIVE",
      billingType: "MONTHLY",
      autoInvoice: true,
      nextInvoiceDate: { lte: now },
    },
    include: { serviceType: true },
  });

  let created = 0;
  let skipped = 0;
  const failed: string[] = [];

  for (const service of dueServices) {
    try {
      const invoiceId = await prisma.$transaction(async (tx) => {
        // Compare-and-swap on nextInvoiceDate: if another invocation already claimed
        // this service (e.g. a manual test run overlapping the real schedule), this
        // update matches zero rows and we skip rather than double-invoice.
        const advanced = await tx.clientService.updateMany({
          where: { id: service.id, nextInvoiceDate: service.nextInvoiceDate },
          data: { nextInvoiceDate: addMonths(service.nextInvoiceDate!, 1) },
        });
        if (advanced.count === 0) return null;

        const issueDate = new Date();
        const invoice = await tx.invoice.create({
          data: {
            clientId: service.clientId,
            title: `${service.serviceType.name}${service.label ? ` — ${service.label}` : ""} — ${format(issueDate, "MMMM yyyy")}`,
            issueDate,
            dueDate: addDays(issueDate, 14),
            autoGenerated: true,
            lineItems: {
              create: [
                {
                  clientServiceId: service.id,
                  description: service.label || service.serviceType.name,
                  quantity: 1,
                  unitPrice: service.priceValue ?? 0,
                  position: 0,
                },
              ],
            },
            activities: {
              create: {
                clientId: service.clientId,
                type: "CREATED",
                message: `Invoice auto-generated for ${service.serviceType.name} (monthly billing)`,
                userId: null,
              },
            },
          },
        });
        return invoice.id;
      });

      if (invoiceId) created += 1;
      else skipped += 1;
    } catch (err) {
      console.error(`generate-recurring-invoices: failed for ClientService ${service.id}`, err);
      failed.push(service.id);
    }
  }

  revalidatePath("/invoices");
  revalidatePath("/dashboard");

  return NextResponse.json({ created, skipped, failed });
}
